# -*- coding: utf-8 -*-
"""
自动生成的技能常量

由 generate_skill_constants.py 从游戏数据生成
"""

# 技能分支翻译 (与 SKILL_OBJECTS 中的 branch 名称对齐)
SKILL_BRANCH_TRANSLATIONS = {
    "2haxe": "双手斧",
    "2hmace": "双手锤棒",
    "2hsword": "双手刀剑",
    "arcanistics": "秘术",
    "armor": "着甲",
    "athletic": "肢体活动",
    "axe": "单手斧",
    "combat": "搏斗",
    "dagger": "匕首",
    "dual": "兵器双持",
    "electromancy": "电术",
    "geomancy": "地术",
    "mace": "单手锤棒",
    "magic_mastery": "驭法",
    "necromancy": "亡灵法",
    "none": "无分支",
    "pyromancy": "炎术",
    "ranged": "远程兵器",
    "sanguimancy": "血术",
    "shield": "盾牌",
    "spear": "长杆刃器",
    "staff": "长杖",
    "sword": "单手刀剑",
    "unknown": "未知",
}

# 技能对象信息
# 格式: {skill_object: {branch, name_chinese, name_english, class, target, ...}}
SKILL_OBJECTS = {
    # ====== 2haxe (2haxe) ======
    "o_skill_wide_cut": {
        "branch": "2haxe",
        "name_chinese": "勾斧",
        "name_english": "Hooking Chop",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_dismember": {
        "branch": "2haxe",
        "name_chinese": "大卸八块",
        "name_english": "Dismember",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_killing_swing": {
        "branch": "2haxe",
        "name_chinese": "夺命",
        "name_english": "Make Space",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_reign_in_blood": {
        "branch": "2haxe",
        "name_chinese": "见血为快",
        "name_english": "Reign in Blood",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_rampage": {
        "branch": "2haxe",
        "name_chinese": "运斤成风",
        "name_english": "Rampage",
        "class": "skill",
        "target": "No Target",
    },

    # ====== 2hmace (2hmace) ======
    "o_skill_skull_crusher": {
        "branch": "2hmace",
        "name_chinese": "劈头盖顶",
        "name_english": "Skull Crusher",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_mayhem": {
        "branch": "2hmace",
        "name_chinese": "大杀四方",
        "name_english": "Striker Stance",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_unstoppable_force": {
        "branch": "2hmace",
        "name_chinese": "所向披靡",
        "name_english": "Unstoppable Force",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_mighty_swing": {
        "branch": "2hmace",
        "name_chinese": "无坚不摧",
        "name_english": "Mighty Swing",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_forceful_slam": {
        "branch": "2hmace",
        "name_chinese": "震天撼地",
        "name_english": "Forceful Slam",
        "class": "skill",
        "target": "Target Object",
    },

    # ====== 2hsword (2hsword) ======
    "o_skill_steel_feast": {
        "branch": "2hsword",
        "name_chinese": "刀剑无情",
        "name_english": "Feast of Steel",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_riposte": {
        "branch": "2hsword",
        "name_chinese": "招架",
        "name_english": "Parry",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_feint_swing": {
        "branch": "2hsword",
        "name_chinese": "断手",
        "name_english": "Hewing Strike",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_arc_cleave": {
        "branch": "2hsword",
        "name_chinese": "猛扫",
        "name_english": "Arc Cleave",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_heroic_charge": {
        "branch": "2hsword",
        "name_chinese": "英勇冲锋",
        "name_english": "Heroic Charge",
        "class": "skill",
        "target": "Target Object",
    },

    # ====== 秘术 (arcanistics) ======
    "o_skill_aether_shield": {
        "branch": "arcanistics",
        "name_chinese": "以太结界",
        "name_english": "Aether Shield",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_mana_crystal_bolt": {
        "branch": "arcanistics",
        "name_chinese": "以太能量",
        "name_english": "Aether Bolt",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_astral_phantasm": {
        "branch": "arcanistics",
        "name_chinese": "幻影",
        "name_english": "Phantasm",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_arcane_tether": {
        "branch": "arcanistics",
        "name_chinese": "秘能束缚",
        "name_english": "Arcane Tether",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_planar_exchange": {
        "branch": "arcanistics",
        "name_chinese": "维度错换",
        "name_english": "Dimensional Shift",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_wormhole": {
        "branch": "arcanistics",
        "name_chinese": "虫洞",
        "name_english": "Wormhole",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_schism": {
        "branch": "arcanistics",
        "name_chinese": "裂隙",
        "name_english": "Schism",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_stasis": {
        "branch": "arcanistics",
        "name_chinese": "静滞",
        "name_english": "Stasis",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_mana_crystal": {
        "branch": "arcanistics",
        "name_chinese": "魔晶",
        "name_english": "Mana Crystal",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_mana_siphoning": {
        "branch": "arcanistics",
        "name_chinese": "魔能虹吸",
        "name_english": "Mana Siphon",
        "class": "spell",
        "target": "Target Object",
    },

    # ====== 着甲 (armor) ======
    "o_skill_active_defence": {
        "branch": "armor",
        "name_chinese": "以攻为守",
        "name_english": "Flexible Defense",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_battering_ram": {
        "branch": "armor",
        "name_chinese": "冲撞",
        "name_english": "Battering Ram",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_unyielding_defence": {
        "branch": "armor",
        "name_chinese": "岿然不动",
        "name_english": "Unyielding Defense",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_brace_for_impact": {
        "branch": "armor",
        "name_chinese": "放马过来！",
        "name_english": "Brace for Impact!",
        "class": "skill",
        "target": "No Target",
    },

    # ====== athletic (athletic) ======
    "o_skill_dash": {
        "branch": "athletic",
        "name_chinese": "前冲",
        "name_english": "Dash",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_sweep": {
        "branch": "athletic",
        "name_chinese": "扫腿",
        "name_english": "Leg Sweep",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_elusiveness": {
        "branch": "athletic",
        "name_chinese": "灵敏",
        "name_english": "Elusiveness",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_adrenaline_rush": {
        "branch": "athletic",
        "name_chinese": "热血澎湃",
        "name_english": "Adrenaline Rush",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_power_kick": {
        "branch": "athletic",
        "name_chinese": "猛踹",
        "name_english": "Mighty Kick",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_sudden_strike": {
        "branch": "athletic",
        "name_chinese": "箭步突袭",
        "name_english": "Sudden Lunge",
        "class": "skill",
        "target": "Target Object",
    },

    # ====== axe (axe) ======
    "o_skill_crippling_lunge": {
        "branch": "axe",
        "name_chinese": "先下手为强",
        "name_english": "Mutilating Lunge",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_massacre": {
        "branch": "axe",
        "name_chinese": "大开杀戒",
        "name_english": "Massacre",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_execution": {
        "branch": "axe",
        "name_chinese": "斩首",
        "name_english": "Execution",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_cut_through": {
        "branch": "axe",
        "name_chinese": "狠劈",
        "name_english": "Cut Through",
        "class": "skill",
        "target": "Target Object",
    },

    # ====== 搏斗 (combat) ======
    "o_skill_against_the_odds": {
        "branch": "combat",
        "name_chinese": "力挽狂澜",
        "name_english": "Against the Odds",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_thirst_for_battle": {
        "branch": "combat",
        "name_chinese": "奋力一搏",
        "name_english": "Thirst for Battle",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_war_cry": {
        "branch": "combat",
        "name_chinese": "战吼",
        "name_english": "War Cry",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_seize_the_initiative": {
        "branch": "combat",
        "name_chinese": "掌握主动",
        "name_english": "Seize the Initiative",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_offensive_tactics": {
        "branch": "combat",
        "name_chinese": "攻击战术",
        "name_english": "Offensive Tactic",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_finisher": {
        "branch": "combat",
        "name_chinese": "最后一击",
        "name_english": "Finisher",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_defensive_tactics": {
        "branch": "combat",
        "name_chinese": "防御战术",
        "name_english": "Defensive Tactic",
        "class": "skill",
        "target": "No Target",
    },

    # ====== dagger (dagger) ======
    "o_skill_double_jab": {
        "branch": "dagger",
        "name_chinese": "寒光有形",
        "name_english": "Double Lunge",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_coup_de_grace": {
        "branch": "dagger",
        "name_chinese": "恩赐解脱",
        "name_english": "Coup de Grace",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_deadly_trick": {
        "branch": "dagger",
        "name_chinese": "斗转星移",
        "name_english": "Deadly Trick",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_gaping_wound": {
        "branch": "dagger",
        "name_chinese": "破伤",
        "name_english": "Gaping Wound",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_painful_stabs": {
        "branch": "dagger",
        "name_chinese": "辣手利刃",
        "name_english": "Painful Stabs",
        "class": "skill",
        "target": "No Target",
    },

    # ====== dual (dual) ======
    "o_skill_enough_for_everyone": {
        "branch": "dual",
        "name_chinese": "人人有份",
        "name_english": "Enough for Everyone",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_honed_moves": {
        "branch": "dual",
        "name_chinese": "全神贯注",
        "name_english": "Concentration",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_deflect": {
        "branch": "dual",
        "name_chinese": "挡避",
        "name_english": "Deflect",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_whirlwind": {
        "branch": "dual",
        "name_chinese": "旋风",
        "name_english": "Whirlwind",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_series_of_strikes": {
        "branch": "dual",
        "name_chinese": "暴风疾雨",
        "name_english": "Flurry of Strikes",
        "class": "skill",
        "target": "Target Object",
    },

    # ====== 电术 (electromancy) ======
    "o_skill_discharge": {
        "branch": "electromancy",
        "name_chinese": "放电",
        "name_english": "Jolt",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_ball_lightning": {
        "branch": "electromancy",
        "name_chinese": "球状闪电",
        "name_english": "Ball Lightning",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_short_circuit": {
        "branch": "electromancy",
        "name_chinese": "短路",
        "name_english": "Short Circuit",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_impulse": {
        "branch": "electromancy",
        "name_chinese": "脉冲",
        "name_english": "Impulse",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_chain_lightning": {
        "branch": "electromancy",
        "name_chinese": "连锁闪电",
        "name_english": "Chain Lightning",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_static_field": {
        "branch": "electromancy",
        "name_chinese": "静态场",
        "name_english": "Static Field",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_tempest": {
        "branch": "electromancy",
        "name_chinese": "风雷大作",
        "name_english": "Tempest",
        "class": "spell",
        "target": "Target Object",
    },

    # ====== 地术 (geomancy) ======
    "o_skill_earth_quake": {
        "branch": "geomancy",
        "name_chinese": "地动山摇",
        "name_english": "Earthquake",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_boulder_toss": {
        "branch": "geomancy",
        "name_chinese": "投石",
        "name_english": "Boulder Toss",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_stone_spikes": {
        "branch": "geomancy",
        "name_chinese": "石刺",
        "name_english": "Stone Spikes",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_petrification": {
        "branch": "geomancy",
        "name_chinese": "石化",
        "name_english": "Petrification",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_stone_armor": {
        "branch": "geomancy",
        "name_chinese": "石甲",
        "name_english": "Stone Armor",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_runic_boulder": {
        "branch": "geomancy",
        "name_chinese": "符文巨石",
        "name_english": "Runic Boulder",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_runic_explosion": {
        "branch": "geomancy",
        "name_chinese": "符文爆炸",
        "name_english": "Runic Explosion",
        "class": "spell",
        "target": "Target Object",
    },

    # ====== mace (mace) ======
    "o_skill_knockout": {
        "branch": "mace",
        "name_chinese": "狠锤",
        "name_english": "Knock Out",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_onslaught": {
        "branch": "mace",
        "name_chinese": "猛攻",
        "name_english": "Onslaught",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_armor_break": {
        "branch": "mace",
        "name_chinese": "破甲",
        "name_english": "Armor Break",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_hammer_and_anvil": {
        "branch": "mace",
        "name_chinese": "锤与铁砧",
        "name_english": "Hammer and Anvil",
        "class": "skill",
        "target": "No Target",
    },

    # ====== 驭法 (magic_mastery) ======
    "o_skill_seal_of_reflection": {
        "branch": "magic_mastery",
        "name_chinese": "反动法印",
        "name_english": "Seal of Reflection",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_seal_of_power": {
        "branch": "magic_mastery",
        "name_chinese": "增强法印",
        "name_english": "Seal of Power",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_seal_of_insight": {
        "branch": "magic_mastery",
        "name_chinese": "明见法印",
        "name_english": "Seal of Insight",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_seal_of_shackles": {
        "branch": "magic_mastery",
        "name_chinese": "禁锢法印",
        "name_english": "Seal of Shackles",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_seal_of_finesse": {
        "branch": "magic_mastery",
        "name_chinese": "精纯法印",
        "name_english": "Seal of Finesse",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_seal_of_cleansing": {
        "branch": "magic_mastery",
        "name_chinese": "荡涤法印",
        "name_english": "Seal of Cleansing",
        "class": "spell",
        "target": "Target Object",
    },

    # ====== necromancy (necromancy) ======
    "o_skill_darkbolt": {
        "branch": "necromancy",
        "name_chinese": "亵渎",
        "name_english": "Desecration",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_befoul_the_remains": {
        "branch": "necromancy",
        "name_chinese": "亵渎遗骸",
        "name_english": "Defiled Remains",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_dark_ressurection": {
        "branch": "necromancy",
        "name_chinese": "低等起死还魂",
        "name_english": "Lesser Ritual of Resurrection",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_baleful_glow": {
        "branch": "necromancy",
        "name_chinese": "凶光",
        "name_english": "Baleful Glow",
        "class": "spell",
        "target": "Target Ally",
    },
    "o_skill_summon_zombie": {
        "branch": "necromancy",
        "name_chinese": "唤尸",
        "name_english": "Summon the Restless",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_phantom_bats": {
        "branch": "necromancy",
        "name_chinese": "幻影蝙蝠",
        "name_english": "Phantom Bats",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_essence_leech": {
        "branch": "necromancy",
        "name_chinese": "摄魄",
        "name_english": "Steal Essence",
        "class": "spell",
        "target": "Target Ally",
    },
    "o_skill_sigil_of_binding": {
        "branch": "necromancy",
        "name_chinese": "有难同当",
        "name_english": "Binding Sigil",
        "class": "spell",
        "target": "Target Ally",
    },
    "o_skill_death_touch": {
        "branch": "necromancy",
        "name_chinese": "死亡之触",
        "name_english": "Death Touch",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_sign_of_darkness": {
        "branch": "necromancy",
        "name_chinese": "渎圣魔印",
        "name_english": "Blasphemous Sigil",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_curse_of_weakness": {
        "branch": "necromancy",
        "name_chinese": "痛苦诅咒",
        "name_english": "Curse of Agony",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_motherly_blessing": {
        "branch": "necromancy",
        "name_chinese": "虫母护佑",
        "name_english": "Motherly Blessing",
        "class": "spell",
        "target": "Target Ally",
    },
    "o_skill_curse": {
        "branch": "necromancy",
        "name_chinese": "衰弱诅咒",
        "name_english": "Curse of Decay",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_unholy_ritual": {
        "branch": "necromancy",
        "name_chinese": "邪术仪式",
        "name_english": "Unholy Ritual",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_dark_blessing": {
        "branch": "necromancy",
        "name_chinese": "邪术庇佑",
        "name_english": "Unholy Blessing",
        "class": "spell",
        "target": "Target Ally",
    },
    "o_skill_dissipation": {
        "branch": "necromancy",
        "name_chinese": "阴魂不散",
        "name_english": "Spectral Haunting",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_soul_sacrifice": {
        "branch": "necromancy",
        "name_chinese": "魂祭",
        "name_english": "Soul Sacrifice",
        "class": "spell",
        "target": "Target Ally",
    },

    # ====== none (none) ======
    "o_skill_blood_craze": {
        "branch": "none",
        "name_chinese": "Blood_Craze",
        "name_english": "Blood_Craze",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_flesh_pile": {
        "branch": "none",
        "name_chinese": "Flesh_Pile",
        "name_english": "Flesh_Pile",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_for_whom_the_bell_tolls": {
        "branch": "none",
        "name_chinese": "丧钟为谁而鸣",
        "name_english": "For Whom The Bell Tolls",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_vengeance_of_the_dead": {
        "branch": "none",
        "name_chinese": "亡灵复仇",
        "name_english": "Vengeance of the Dead",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_lay_the_eggs": {
        "branch": "none",
        "name_chinese": "产卵",
        "name_english": "Egg Clutch",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_animated_servant": {
        "branch": "none",
        "name_chinese": "仆从复苏",
        "name_english": "Animated Servant",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_primal_aether": {
        "branch": "none",
        "name_chinese": "元初以太",
        "name_english": "Primal Aether",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_shockwave": {
        "branch": "none",
        "name_chinese": "冲击波",
        "name_english": "Shockwave",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_craft": {
        "branch": "none",
        "name_chinese": "制作",
        "name_english": "Crafting",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_leap_forward": {
        "branch": "none",
        "name_chinese": "前扑",
        "name_english": "Spider Leap",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_butchering": {
        "branch": "none",
        "name_chinese": "剖解",
        "name_english": "Butchering",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_regurgitate": {
        "branch": "none",
        "name_chinese": "反刍",
        "name_english": "Regurgitate",
        "class": "skill",
        "target": "Target Ally",
    },
    "o_skill_backwards_dash": {
        "branch": "none",
        "name_chinese": "后撤",
        "name_english": "Jump Away",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_web_spit": {
        "branch": "none",
        "name_chinese": "吐丝结网",
        "name_english": "Web Spit",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_corpse_devourment": {
        "branch": "none",
        "name_chinese": "吞尸",
        "name_english": "Corpse Devourment",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_grab_em": {
        "branch": "none",
        "name_chinese": "咬住！",
        "name_english": "Grab 'Em!",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_scream_of_doom": {
        "branch": "none",
        "name_chinese": "哀号",
        "name_english": "Baleful Scream",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_summon_the_hive": {
        "branch": "none",
        "name_chinese": "唤巢",
        "name_english": "Summon the Hive",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_summon_the_worm": {
        "branch": "none",
        "name_chinese": "唤虫",
        "name_english": "Summon Worm",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_blood_spit": {
        "branch": "none",
        "name_chinese": "啐血",
        "name_english": "Blood Spit",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_taste_the_flesh": {
        "branch": "none",
        "name_chinese": "啖肉",
        "name_english": "Taste for Flesh",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_drink_potion": {
        "branch": "none",
        "name_chinese": "喝药",
        "name_english": "Drink Potion",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_vampiric_blood": {
        "branch": "none",
        "name_chinese": "嗜血",
        "name_english": "Bloodthirst",
        "class": "attack",
        "target": "Target Object",
    },
    "o_skill_deadly_tail": {
        "branch": "none",
        "name_chinese": "夺命尾",
        "name_english": "Deadly Tail",
        "class": "attack",
        "target": "Target Object",
    },
    "o_skill_venomous_salvo": {
        "branch": "none",
        "name_chinese": "射毒",
        "name_english": "Toxic Salvo",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_peck": {
        "branch": "none",
        "name_chinese": "尖喙",
        "name_english": "Peck",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_grave_cold": {
        "branch": "none",
        "name_chinese": "尸寒逼人",
        "name_english": "Grave Chill",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_troll_regeneration": {
        "branch": "none",
        "name_chinese": "巨魔自动恢复",
        "name_english": "Troll Regeneration",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_murk_strike": {
        "branch": "none",
        "name_chinese": "幽袭",
        "name_english": "Murkstrike",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_loud_barking": {
        "branch": "none",
        "name_chinese": "怒吠",
        "name_english": "Loud Barking",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_drums_of_war": {
        "branch": "none",
        "name_chinese": "战鼓",
        "name_english": "Drums of War",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_tunnel_through": {
        "branch": "none",
        "name_chinese": "打洞",
        "name_english": "Tunnel Through",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_throw_bee_bomb": {
        "branch": "none",
        "name_chinese": "投掷亡蜂罐",
        "name_english": "Deathstinger Jar Throw",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_rock_toss": {
        "branch": "none",
        "name_chinese": "投掷巨石",
        "name_english": "Rock Toss",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_throw_fire_bomb": {
        "branch": "none",
        "name_chinese": "投掷火焰瓶",
        "name_english": "Flame Flask Throw",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_throw_acid_bomb": {
        "branch": "none",
        "name_chinese": "投掷酸液瓶",
        "name_english": "Acid Flask Throw",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_protect_the_hive": {
        "branch": "none",
        "name_chinese": "护巢",
        "name_english": "Protect the Hive",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_fling_away": {
        "branch": "none",
        "name_chinese": "抽打",
        "name_english": "Fling Away",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_wraith_summoning": {
        "branch": "none",
        "name_chinese": "招魂",
        "name_english": "Wraith Summoning",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_trap_search": {
        "branch": "none",
        "name_chinese": "探查",
        "name_english": "Examine Surroundings",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_raise_the_banner": {
        "branch": "none",
        "name_chinese": "摇旗！",
        "name_english": "Banners High!",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_destructive_force": {
        "branch": "none",
        "name_chinese": "摧枯拉朽",
        "name_english": "Devastating Power",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_net_throw": {
        "branch": "none",
        "name_chinese": "撒网",
        "name_english": "Net Throw",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_throw_caltrop": {
        "branch": "none",
        "name_chinese": "撒蒺藜",
        "name_english": "Caltrops Throw",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_tremor_strike": {
        "branch": "none",
        "name_chinese": "撼地重击",
        "name_english": "Earthshaking Strike",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_tremor_strike_troll": {
        "branch": "none",
        "name_chinese": "撼地重击",
        "name_english": "Earthshaking Strike",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_strangling_grasp": {
        "branch": "none",
        "name_chinese": "攫命",
        "name_english": "Strangling Grasp",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_bloodletting": {
        "branch": "none",
        "name_chinese": "放血",
        "name_english": "Lacerate",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_final_stand": {
        "branch": "none",
        "name_chinese": "最后一搏",
        "name_english": "Last Stand",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_deadly_premonition": {
        "branch": "none",
        "name_chinese": "死兆",
        "name_english": "Deadly Premonition",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_herald_of_ruination": {
        "branch": "none",
        "name_chinese": "毁灭将至",
        "name_english": "Herald of Ruination",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_jagged_spike": {
        "branch": "none",
        "name_chinese": "毒刺",
        "name_english": "Poisoned Spike",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_will_to_survive": {
        "branch": "none",
        "name_chinese": "求生欲",
        "name_english": "Will to Survive",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_dead_or_alive": {
        "branch": "none",
        "name_chinese": "活要人死要尸",
        "name_english": "Dead or Alive",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_predigest": {
        "branch": "none",
        "name_chinese": "消化液",
        "name_english": "Predigest",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_torch_strike": {
        "branch": "none",
        "name_chinese": "火把攻击",
        "name_english": "Torch Strike",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_cauterize_wounds": {
        "branch": "none",
        "name_chinese": "烧灼创口",
        "name_english": "Cauterize Wounds",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_instigate": {
        "branch": "none",
        "name_chinese": "煽动",
        "name_english": "Instigate",
        "class": "skill",
        "target": "Target Ally",
    },
    "o_skill_burning_offering": {
        "branch": "none",
        "name_chinese": "燔祭",
        "name_english": "Burnt Offering",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_blister_burst": {
        "branch": "none",
        "name_chinese": "爆脓",
        "name_english": "Blister Burst",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_troll_clout": {
        "branch": "none",
        "name_chinese": "爪击横扫",
        "name_english": "Claw Swipe",
        "class": "attack",
        "target": "Target Object",
    },
    "o_skill_bestial_charge": {
        "branch": "none",
        "name_chinese": "狂冲",
        "name_english": "Bestial Charge",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_rapid_flight": {
        "branch": "none",
        "name_chinese": "狂飞",
        "name_english": "Rapid Flight",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_howl": {
        "branch": "none",
        "name_chinese": "狼嗥",
        "name_english": "Howl",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_lacerate": {
        "branch": "none",
        "name_chinese": "皮开肉绽",
        "name_english": "Rend Flesh",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_false_promises": {
        "branch": "none",
        "name_chinese": "空口白话",
        "name_english": "False Promises",
        "class": "skill",
        "target": "Target Ally",
    },
    "o_skill_charge_ram": {
        "branch": "none",
        "name_chinese": "突奔",
        "name_english": "Ramming Charge",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_first_aid": {
        "branch": "none",
        "name_chinese": "紧急处理",
        "name_english": "First Aid",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_sic_em": {
        "branch": "none",
        "name_chinese": "给我上！",
        "name_english": "Sic!",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_tongue_leech": {
        "branch": "none",
        "name_chinese": "舌吸血",
        "name_english": "Tongue Leech",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_tongue_pull": {
        "branch": "none",
        "name_chinese": "舌拉",
        "name_english": "Tongue Pull",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_tongue_push": {
        "branch": "none",
        "name_chinese": "舌推",
        "name_english": "Tongue Push",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_brand_of_anguish": {
        "branch": "none",
        "name_chinese": "苦痛烙印",
        "name_english": "Brand of Anguish",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_flesh_explosion": {
        "branch": "none",
        "name_chinese": "血肉横飞",
        "name_english": "Flesh Explosion",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_tentacle_arm": {
        "branch": "none",
        "name_chinese": "触手",
        "name_english": "Tentacle Arm",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_swipe": {
        "branch": "none",
        "name_chinese": "重扫",
        "name_english": "Wild Swipe",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_dig_in": {
        "branch": "none",
        "name_chinese": "钻地",
        "name_english": "Undermine",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_chain_strike": {
        "branch": "none",
        "name_chinese": "锁链重抽",
        "name_english": "Chain Strike",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_coals_and_embers": {
        "branch": "none",
        "name_chinese": "阴燃炭灰",
        "name_english": "Fiery Embers",
        "class": "skill",
        "target": "Target Area",
    },
    "o_skill_deafening_roar": {
        "branch": "none",
        "name_chinese": "震天怒吼",
        "name_english": "Deafening Roar",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_lash_blessing": {
        "branch": "none",
        "name_chinese": "鞭挞",
        "name_english": "Lash Blessing",
        "class": "skill",
        "target": "Target Ally",
    },
    "o_skill_throw_dagger": {
        "branch": "none",
        "name_chinese": "飞刀",
        "name_english": "Dagger Throw",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_lion_charge": {
        "branch": "none",
        "name_chinese": "飞扑",
        "name_english": "Lion Leap",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_throw_axe": {
        "branch": "none",
        "name_chinese": "飞斧",
        "name_english": "Hatchet Throw",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_cannibalistic_craze": {
        "branch": "none",
        "name_chinese": "食人狂乱",
        "name_english": "Cannibalistic Craze",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_necrophagy": {
        "branch": "none",
        "name_chinese": "食尸",
        "name_english": "Necrophage",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_grimace_of_terror": {
        "branch": "none",
        "name_chinese": "骇人之相",
        "name_english": "Face of Horror",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_bone_fires": {
        "branch": "none",
        "name_chinese": "骨焰",
        "name_english": "Bone Pyres",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_bone_throw": {
        "branch": "none",
        "name_chinese": "骸袭",
        "name_english": "Bone Throw",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_elder_ritual_of_resurrection": {
        "branch": "none",
        "name_chinese": "高等起死还魂",
        "name_english": "Greater Ritual of Resurrection",
        "class": "spell",
        "target": "No Target",
    },

    # ====== 炎术 (pyromancy) ======
    "o_skill_magma_rain": {
        "branch": "pyromancy",
        "name_chinese": "岩浆之雨",
        "name_english": "Magma Rain",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_flame_wave": {
        "branch": "pyromancy",
        "name_chinese": "火浪",
        "name_english": "Flame Wave",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_flame_ring": {
        "branch": "pyromancy",
        "name_chinese": "火环",
        "name_english": "Ring of Fire",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_inferno": {
        "branch": "pyromancy",
        "name_chinese": "炎狱",
        "name_english": "Inferno",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_incineration": {
        "branch": "pyromancy",
        "name_chinese": "焚烬",
        "name_english": "Incineration",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_melting_ray": {
        "branch": "pyromancy",
        "name_chinese": "熔岩之火",
        "name_english": "Melting Ray",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_fire_barrage": {
        "branch": "pyromancy",
        "name_chinese": "连发火球",
        "name_english": "Fire Barrage",
        "class": "spell",
        "target": "Target Point",
    },

    # ====== ranged (ranged) ======
    "o_skill_suppression": {
        "branch": "ranged",
        "name_chinese": "压制",
        "name_english": "Suppression",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_pierce_through_missile": {
        "branch": "ranged",
        "name_chinese": "慑敌连发",
        "name_english": "Startling Volley",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_hunters_mark": {
        "branch": "ranged",
        "name_chinese": "猎人印记",
        "name_english": "Hunter's Mark",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_headshot": {
        "branch": "ranged",
        "name_chinese": "直取首级",
        "name_english": "Headshot",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_taking_aim": {
        "branch": "ranged",
        "name_chinese": "瞄准",
        "name_english": "Taking Aim",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_distracting_shot": {
        "branch": "ranged",
        "name_chinese": "转移注意",
        "name_english": "Distracting Shot",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_long_range_shot": {
        "branch": "ranged",
        "name_chinese": "远射",
        "name_english": "Long Shot",
        "class": "skill",
        "target": "Target Point",
    },

    # ====== sanguimancy (sanguimancy) ======
    "o_skill_willing_sacrifice": {
        "branch": "sanguimancy",
        "name_chinese": "Willing_Sacrifice",
        "name_english": "Willing_Sacrifice",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_summon_blood_golem": {
        "branch": "sanguimancy",
        "name_chinese": "召唤赤血魔像",
        "name_english": "Summon Blood Golem",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_life_leech": {
        "branch": "sanguimancy",
        "name_chinese": "吸血",
        "name_english": "Life Leech",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_vampire_rune": {
        "branch": "sanguimancy",
        "name_chinese": "吸血魔印",
        "name_english": "Draining Sigil",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_mark_of_the_feast": {
        "branch": "sanguimancy",
        "name_chinese": "在劫难逃",
        "name_english": "Mark of the Feast",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_murkwalk": {
        "branch": "sanguimancy",
        "name_chinese": "幽行",
        "name_english": "Murkwalk",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_embrace_the_murk": {
        "branch": "sanguimancy",
        "name_chinese": "幽隐",
        "name_english": "Embrace the Murk",
        "class": "spell",
        "target": "Target Point",
    },
    "o_skill_blood_puddle": {
        "branch": "sanguimancy",
        "name_chinese": "沸血",
        "name_english": "Blood Puddle",
        "class": "spell",
        "target": "Target Area",
    },
    "o_skill_unholy_anthems": {
        "branch": "sanguimancy",
        "name_chinese": "渎神曲",
        "name_english": "Unholy Anthems",
        "class": "spell",
        "target": "No Target",
    },
    "o_skill_wormrot": {
        "branch": "sanguimancy",
        "name_chinese": "虫食",
        "name_english": "Wormfood",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_blood_clot": {
        "branch": "sanguimancy",
        "name_chinese": "血块",
        "name_english": "Blood Clot",
        "class": "spell",
        "target": "Target Object",
    },
    "o_skill_sacrificial_blood": {
        "branch": "sanguimancy",
        "name_chinese": "血祭",
        "name_english": "Sacrificial Blood",
        "class": "spell",
        "target": "Target Object",
    },

    # ====== shield (shield) ======
    "o_skill_raise_shield": {
        "branch": "shield",
        "name_chinese": "举盾",
        "name_english": "Raise Shield",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_defensive_stance": {
        "branch": "shield",
        "name_chinese": "寸步不让！",
        "name_english": "Hold the Line!",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_ram": {
        "branch": "shield",
        "name_chinese": "盾击",
        "name_english": "Shield Bash",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_breakthrough": {
        "branch": "shield",
        "name_chinese": "突围",
        "name_english": "Breakthrough",
        "class": "skill",
        "target": "Target Area",
    },

    # ====== spear (spear) ======
    "o_skill_intransigence": {
        "branch": "spear",
        "name_chinese": "寸土必争",
        "name_english": "Determination",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_nail_down": {
        "branch": "spear",
        "name_chinese": "尖矛",
        "name_english": "Nail Down",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_regroup": {
        "branch": "spear",
        "name_chinese": "应变",
        "name_english": "Regroup",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_pikemans_stance": {
        "branch": "spear",
        "name_chinese": "枪兵站姿",
        "name_english": "Pikeman Stance",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_piercing_lunge": {
        "branch": "spear",
        "name_chinese": "突刺",
        "name_english": "Impaling Lunge",
        "class": "skill",
        "target": "Target Area",
    },

    # ====== staff (staff) ======
    "o_skill_unwavering_stance": {
        "branch": "staff",
        "name_chinese": "不动不摇",
        "name_english": "Unwavering Stance",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_hail_of_blows": {
        "branch": "staff",
        "name_chinese": "乱杖",
        "name_english": "Hail of Blows",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_peacemaker": {
        "branch": "staff",
        "name_chinese": "和为贵",
        "name_english": "Peacemaker",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_step_aside": {
        "branch": "staff",
        "name_chinese": "让开！",
        "name_english": "Step Aside!",
        "class": "skill",
        "target": "Target Object",
    },

    # ====== sword (sword) ======
    "o_skill_keeping_distance": {
        "branch": "sword",
        "name_chinese": "保持距离",
        "name_english": "Keeping Distance",
        "class": "skill",
        "target": "Target Point",
    },
    "o_skill_advance": {
        "branch": "sword",
        "name_chinese": "冲前一击",
        "name_english": "Onrush",
        "class": "skill",
        "target": "Target Object",
    },
    "o_skill_fencer_stance": {
        "branch": "sword",
        "name_chinese": "刀剑站姿",
        "name_english": "Fencer Stance",
        "class": "skill",
        "target": "No Target",
    },
    "o_skill_cleave": {
        "branch": "sword",
        "name_chinese": "横扫",
        "name_english": "Cleaving Strike",
        "class": "skill",
        "target": "Target Area",
    },

    # ====== unknown (unknown) ======
    "o_skill_crimson_banner": {
        "branch": "unknown",
        "name_chinese": "Crimson_Banner",
        "name_english": "Crimson_Banner",
        "class": "unknown",
        "target": "unknown",
    },
    "o_skill_emergency_repair": {
        "branch": "unknown",
        "name_chinese": "Emergency_Repair",
        "name_english": "Emergency_Repair",
        "class": "unknown",
        "target": "unknown",
    },
    "o_skill_lightning_enchantment": {
        "branch": "unknown",
        "name_chinese": "Lightning_Enchantment",
        "name_english": "Lightning_Enchantment",
        "class": "unknown",
        "target": "unknown",
    },
    "o_skill_sleep": {
        "branch": "unknown",
        "name_chinese": "Sleep",
        "name_english": "Sleep",
        "class": "unknown",
        "target": "unknown",
    },
    "o_skill_Tantum": {
        "branch": "unknown",
        "name_chinese": "Tantrum",
        "name_english": "Tantrum",
        "class": "unknown",
        "target": "unknown",
    },

}

# 动态生成：技能对象名 -> 中文名
SKILL_OBJECT_NAMES = {
    skill_obj: info["name_chinese"]
    for skill_obj, info in SKILL_OBJECTS.items()
}

# 动态生成：按分支分组的技能列表
def _build_skill_by_branch():
    """根据 SKILL_OBJECTS 构建按分支分组的技能字典"""
    result = {}
    for skill_obj, info in SKILL_OBJECTS.items():
        branch = info.get("branch", "unknown")
        if branch not in result:
            result[branch] = []
        result[branch].append(skill_obj)
    return result

SKILL_BY_BRANCH = _build_skill_by_branch()
