# -*- coding: utf-8 -*-
"""UI 协议定义 - 为 Mixin 提供类型标注支持

使用 Protocol 和 TYPE_CHECKING 让 Mixin 能够获得完整的类型检查和 IDE 智能提示，
而不需要在运行时引入循环依赖。

使用方式：
    from typing import TYPE_CHECKING
    if TYPE_CHECKING:
        from ui.protocols import GUIProtocol

    class SomeMixin:
        def some_method(self: "GUIProtocol"):
            self.project.weapons  # IDE 可以正确推断类型
"""

from typing import TYPE_CHECKING, Protocol, Any

if TYPE_CHECKING:
    from models import ModProject, Weapon, Armor
    from hybrid_item_v2 import HybridItemV2
    from specs import Origin
    import types


class GUIProtocol(Protocol):
    """主 GUI 类的协议定义

    定义所有 Mixin 可能需要访问的属性和方法。
    这使得 IDE 能够在 Mixin 中正确推断 self 的类型。

    注意: 配置相关属性 (font_size, is_dark_theme 等) 已迁移到 ui.config 模块。
    这些属性现在作为向后兼容的 property 存在于 GUI 类中。
    """

    # ==================== 核心属性 ====================
    project: "ModProject"
    layout: "types.ModuleType"  # 向后兼容属性，返回 styles 模块
    font_size: int    # 向后兼容属性，返回 config.get_font_size()
    texture_scale: float  # 向后兼容属性，返回 config.get_texture_scale()

    # ==================== 主题相关 ====================
    theme_colors: dict[str, tuple[float, float, float, float]]

    # ==================== 索引状态 ====================
    current_weapon_index: int
    current_armor_index: int
    current_hybrid_index: int

    # ==================== 贴图相关 ====================
    selected_model: str
    selected_race: str
    preview_states: dict[str, Any]
    gender_tab_index: int

    # ==================== 窗口 ====================
    window: Any  # glfw window
    renderer: Any  # GlfwRenderer

    # ==================== ThemeMixin 方法 ====================
    def apply_theme(self) -> None: ...
    def text_secondary(self, text: str) -> None: ...
    def text_success(self, text: str) -> None: ...
    def text_warning(self, text: str) -> None: ...
    def text_error(self, text: str) -> None: ...
    def text_accent(self, text: str) -> None: ...

    # ==================== MenuMixin 方法 ====================
    def draw_main_menu(self) -> None: ...

    # ==================== ItemListMixin 方法 ====================
    def draw_item_panel(self, panel_id: str, items: list, current_index_attr: str,
                        draw_list_func: Any, draw_editor_func: Any, empty_hint: str) -> None: ...
    def draw_weapon_list(self) -> None: ...
    def draw_armor_list(self) -> None: ...
    def draw_hybrid_list(self) -> None: ...

    # ==================== CommonEditorMixin 方法 ====================
    def _draw_enum_combo(self, label: str, current_value: Any, options: list, labels: dict, tooltip_text: str = "") -> Any: ...
    def _draw_mode_combo(self, label: str, current_enum: Any, enum_class: type, labels: dict,
                         options: list | None = None, tooltip_text: str = "") -> Any: ...
    def _draw_inline_checkbox(self, label: str, value: bool, tooltip_text: str = "") -> bool: ...
    def _draw_validation_errors(self, errors: list[str]) -> None: ...
    def draw_indented_separator(self) -> None: ...
    def _draw_basic_properties(self, item: Any, id_suffix: str, slot_labels: dict, material_labels: dict) -> None: ...
    def _draw_attributes_editor(self, item: Any, attribute_groups: dict, id_suffix: str) -> None: ...
    def _draw_fragments_editor(self, armor: "Armor") -> None: ...
    def _draw_localization_editor(self, item: Any, id_suffix: str) -> None: ...

    # ==================== HybridEditorMixin 方法 ====================
    def draw_hybrid_editor(self) -> None: ...
    def _draw_hybrid_base(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_hybrid_behavior(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_hybrid_stats(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_hybrid_presentation(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_hybrid_spawn_settings(self, hybrid: "HybridItemV2") -> None: ...
    def _should_show_hybrid_attributes(self, hybrid: "HybridItemV2") -> bool: ...
    def _draw_hybrid_attributes_editor(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_hybrid_consumable_attributes_editor(self, hybrid: "HybridItemV2") -> None: ...
    def _get_hybrid_attribute_groups(self, hybrid: "HybridItemV2") -> dict: ...
    def _update_hybrid_rarity_from_quality(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_generation_preview_popup(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_container_preview_simplified(self, hybrid: "HybridItemV2", is_equipment: bool) -> None: ...
    def _draw_shop_preview_simplified(self, hybrid: "HybridItemV2") -> None: ...
    def _draw_fragments_popup(self, hybrid: "HybridItemV2") -> None: ...
    def _render_attribute_grid(self, display_list: list, target_dict: dict, hybrid: "HybridItemV2 | None" = None, show_add_button: bool = False, add_button_label: str = "", add_popup_id: str = "") -> list: ...
    def _draw_add_attribute_popup(self, popup_id: str, target_dict: dict, available_attrs: list) -> None: ...
    def _prune_hybrid_attributes(self, hybrid: "HybridItemV2", groups: dict) -> None: ...

    # HybridEditorMixin 状态
    _attr_search_buffers: dict[str, str]

    # ==================== 生成相关 ====================
    def _execute_generation(self) -> None: ...
